#!/bin/bash

case "$1" in
    configure)
    
        # lazydocker
        echo "Install lazydocker..."        
        curl -s https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash >/dev/null 2>&1 || true

        # ttyd
        echo "Install ttyd..."        
        sudo wget https://github.com/tsl0922/ttyd/releases/download/1.7.4/ttyd.i686 -O /usr/local/bin/ttyd >/dev/null 2>&1 || true
        sudo chmod +x /usr/local/bin/ttyd

        # sysz
        echo "Install sysz..."        
        sudo wget https://github.com/joehillen/sysz/releases/latest/download/sysz -O /usr/local/bin/sysz >/dev/null 2>&1 || true
        sudo chmod +x /usr/local/bin/sysz

        # remote-share-cli
        echo "Install remote-share-cli..."        
        npm install -g remote-share-cli >/dev/null 2>&1 || true

        # web-search-cli
        echo "Install web-search-cli..."
        rm -rf /tmp/s-linux_amd64* || true
        wget https://github.com/zquestz/s/releases/download/v0.6.9/s-linux_amd64.zip -O /tmp/s-linux_amd64.zip >/dev/null 2>&1 || true
        unzip /tmp/s-linux_amd64.zip -d /tmp >/dev/null 2>&1 || true
        sudo cp -af /tmp/s-linux_amd64/s /usr/local/bin/s >/dev/null 2>&1 || true
        sudo chmod +x /usr/local/bin/s >/dev/null 2>&1 || true

        echo "Refresh fc-cache..."        
        fc-cache -v -f >/dev/null 2>&1 || true

        echo "Done."                
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
